SELECT m.product_id, p.product_name, m.report_year, m.total_amount
FROM (
        SELECT
            PRODUCT_ID,
            '2018' AS REPORT_YEAR,
            CASE
                WHEN YEAR(PERIOD_START)='2018' AND YEAR(PERIOD_END)='2018' THEN DATEDIFF(DAY, PERIOD_START, PERIOD_END)*AVERAGE_DAILY_SALES+AVERAGE_DAILY_SALES
                WHEN YEAR(PERIOD_START)!='2018' AND YEAR (PERIOD_END)='2018' THEN DATEDIFF(DAY, '2018-01-01', PERIOD_END)*AVERAGE_DAILY_SALES+AVERAGE_DAILY_SALES
                WHEN YEAR(PERIOD_START)='2018' AND YEAR (PERIOD_END)!='2018' THEN DATEDIFF(DAY, PERIOD_START, '2018-12-31')*AVERAGE_DAILY_SALES+AVERAGE_DAILY_SALES
                ELSE DATEDIFF(DAY, '2018-01-01', '2018-12-31')*AVERAGE_DAILY_SALES+AVERAGE_DAILY_SALES
            END AS TOTAL_AMOUNT
        FROM
            SALES
        WHERE
            '2018' BETWEEN YEAR(PERIOD_START) AND YEAR(PERIOD_END)

        UNION

        SELECT
            PRODUCT_ID,
            '2019' AS REPORT_YEAR,
            CASE
                WHEN YEAR(PERIOD_START)='2019' AND YEAR(PERIOD_END)='2019' THEN DATEDIFF(DAY, PERIOD_START, PERIOD_END)*AVERAGE_DAILY_SALES+AVERAGE_DAILY_SALES
                WHEN YEAR(PERIOD_START)!='2019' AND YEAR (PERIOD_END)='2019' THEN DATEDIFF(DAY, '2019-01-01', PERIOD_END)*AVERAGE_DAILY_SALES+AVERAGE_DAILY_SALES
                WHEN YEAR(PERIOD_START)='2019' AND YEAR (PERIOD_END)!='2019' THEN DATEDIFF(DAY, PERIOD_START, '2019-12-31')*AVERAGE_DAILY_SALES+AVERAGE_DAILY_SALES
                ELSE DATEDIFF(DAY, '2019-01-01', '2019-12-31')*AVERAGE_DAILY_SALES+AVERAGE_DAILY_SALES
            END AS TOTAL_AMOUNT
        FROM
            SALES
        WHERE
            '2019' BETWEEN YEAR(PERIOD_START) AND YEAR(PERIOD_END)

        UNION

        SELECT
            PRODUCT_ID,
            '2020' AS REPORT_YEAR,
            CASE
                WHEN YEAR(PERIOD_START)='2020' AND YEAR(PERIOD_END)='2020' THEN DATEDIFF(DAY, PERIOD_START, PERIOD_END)*AVERAGE_DAILY_SALES+AVERAGE_DAILY_SALES
                WHEN YEAR(PERIOD_START)!='2020' AND YEAR (PERIOD_END)='2020' THEN DATEDIFF(DAY, '2020-01-01', PERIOD_END)*AVERAGE_DAILY_SALES+AVERAGE_DAILY_SALES
                WHEN YEAR(PERIOD_START)='2020' AND YEAR (PERIOD_END)!='2020' THEN DATEDIFF(DAY, PERIOD_START, '2020-12-31')*AVERAGE_DAILY_SALES+AVERAGE_DAILY_SALES
                ELSE DATEDIFF(DAY, '2020-01-01', '2020-12-31')*AVERAGE_DAILY_SALES+AVERAGE_DAILY_SALES
            END AS TOTAL_AMOUNT
        FROM
            SALES
        WHERE
            '2020' BETWEEN YEAR(PERIOD_START) AND YEAR(PERIOD_END)
    ) m
LEFT JOIN Product p
ON m.product_id = p.product_id